### ISSUE TITLE
[1.20.4][neoforge] GrowableOres breaks Mekanism paxels

### ISSUE THREAD

**Issue by jstansel** [skniro/GrowableOres#11]
Thanks for the new version! I am super excited to have slime and glowstone reeds now. Unfortunately I use mekanism paxels extensively and this version stops them from being recognized as any of pickaxe, shovel or axe. It's really strange to me how this could happen.

I reproduced with only mekanism and a handful of qualify of life mods. The stone paxel works as expected without GrowableOres and stops working after adding GrowableOres.

NeoForge: 20.4.234
Mekanism: Tools: 10.5.19
Skniro's GrowableOres: 1.3.2-1.20.4-NeoForge

Thanks!

**Comment by skniro** [comment]
Fix in 1.7.4(Fabric）1.4.0（Forge）
