### ISSUE TITLE
Feature Request: Add energized power tin ore (fabric 1.21)

### ISSUE THREAD

**Issue by Knito58** [skniro/GrowableOres#20]
There are already many tin ores supported but if you only have "energized power" as tech mod installed then there's yet no support available.

Please support tin reeds from energized power.

This ist the tag for the ingot =>   **`energizedpower:tin_ingot`**

Thank you

**Comment by Knito58** [comment]
And there is more:

:steel_ingot
:redstone_alloy_ingot
:advanced_alloy_ingot
:energized_copper_ingot
:energized_gold_ingot

ok that would really be overpowered.

**Comment by gilnett** [comment]
Try using the "almost unified" mod. Normally, it merges all identical types of ores. This ensures that if you use tin from another mod, it will also work.
https://www.curseforge.com/minecraft/mc-mods/almost-unified 

Also, try "polymorph." It allows you to choose the crafting output you want to receive in the crafting table.
https://www.curseforge.com/minecraft/mc-mods/polymorph
But indeed, it would be good to have the ores from Energized Power.

**Comment by Knito58** [comment]
Yep energized power did not like unified ingots yet. I tried that on earlier MC versions. As of now, only polymorph is available on 1.21 fabric. Which I have installed and it does not help if there's no conflicting recipe available.

**Comment by skniro** [comment]
> And there is more:
> 
> :steel_ingot :redstone_alloy_ingot :advanced_alloy_ingot :energized_copper_ingot :energized_gold_ingot
> 
> ok that would really be overpowered.

Is all need add item? I want add it to games one time.

**Comment by skniro** [comment]
![image](https://github.com/user-attachments/assets/ed154046-ac84-47b2-8395-1c539628b73c)
Plan add ore cane.

**Comment by Knito58** [comment]
Thank you!

**Comment by Knito58** [comment]
Did you really implement it for Fabric? It is not there yet. I trusted the "Fabric First" label - but now saw a version for Forge with EP support. Is it still in the queue?

**Comment by skniro** [comment]
Are you kidding me? It published in 3 days ago. ![image](https://github.com/user-attachments/assets/f6091106-f471-445a-9489-5a4970387912)

**Comment by Knito58** [comment]
![2024-07-25_202926](https://github.com/user-attachments/assets/42bceddd-9e5e-4eba-9631-82116caf2da9)

Not trying to kid you at all - this is what I see in the Modrinth app.

**Comment by gilnett** [comment]
The mod fabrics are separated in another page

**Comment by Knito58** [comment]
I made a fabric 1.21 profile. All I can see with that profile are mods that were tagged as "fabric" and "1.21". When I "clear filter" and only look at 1.21 then I see that:
![2024-07-25_220843](https://github.com/user-attachments/assets/9fb501eb-17bc-4bd1-972e-aab503ed952c)
There is no 2.4.0 version visible for me. For you, there is one as I can see in your screenshot.

**Comment by gilnett** [comment]
You are not on the fabric page, you are on the forge page

**Comment by Knito58** [comment]
Modrinth App hides away anything that is not Fabric when I hit "Versions". The filter is "Fabric" and "1.21". I do not do anything but clicking "Versions". Modrinth knows my profile and preselects the correct filters for me. I have to clear filters to see other versions. That is how I learned about successful EP support for other versions. I would love to be able to see the 2.4.0 version which supports EP. I can only move to Forge page when clearing filters and resetting them.
![2024-07-26_093412](https://github.com/user-attachments/assets/a90f4ab3-3d1c-4364-ae48-765af53fbda7)

**Comment by Knito58** [comment]
What can I do better?

please help

**Comment by skniro** [comment]
Sorry,I forgot to check modrinth. The update in modrinth upload fail. I will upload it again. Thanks your report.

**Comment by skniro** [comment]
> The mod fabrics are separated in another page

In modrinth only have one page.

**Comment by Knito58** [comment]
Thank you very much for your help. The new version is now visible and installable for my Fabric 1.21 version in the Modrinth App.

**Comment by Knito58** [comment]
![2024-07-26_105919](https://github.com/user-attachments/assets/b754de96-c369-45b3-81d8-125a2255fb0d)
