### ISSUE TITLE
Tin ingot (mekanism) recipe switched to uranium cane from tin cane

### ISSUE THREAD

**Issue by Aurytis11** [skniro/GrowableOres#21]
For some reason the tin ingot recipe randomly switched to uranium cane but used to be tin cane a week ago (when i last played) and i didn't do anything with the mod files in between the time i last played and now (when i posted the issue) and the bug isn't world specific and i also redownloaded the file and it didn't fix the bug. Attached some screenshots of the bug.
![Screenshot (3)](https://github.com/user-attachments/assets/5c02428e-5d5b-4c9a-bcee-261cdd1e7fb1)
![Screenshot (4)](https://github.com/user-attachments/assets/769fe7e4-9e5c-4c25-816c-8ff5da1bd540)

**Comment by skniro** [comment]
Fix in 2.4.1 or 2.4.2(minecraft 1.18)
