### ISSUE TITLE
Reeds craft into wrong result

### ISSUE THREAD

**Issue by ghost** [skniro/GrowableOres#24]
- `growable_ores:bauxite_cane` crafts `techreborn:aluminum_ingot`
![image](https://github.com/user-attachments/assets/fe7c0cc4-74dd-441a-aedd-66b79e746128)
![image](https://github.com/user-attachments/assets/1f245bc1-95fe-444d-a812-75384a49d699)

- `growable_ores:sphalerite_cane` crafts `techreborn:zinc_ingot`
![image](https://github.com/user-attachments/assets/ecd157f5-612d-4f45-9bdf-6a5dc44b6351)
![image](https://github.com/user-attachments/assets/2ca15eb6-3b3a-4c33-a863-749523f44059)

mod version:
GrowableOres-2.4.1-1.20.1-Fabric

**Comment by skniro** [comment]
It not a wrong. If you try craft cane, I will know it is right.
