### ISSUE TITLE
The Create Mechanical Harvester Duplicator

### ISSUE THREAD

**Issue by Antstone2898** [skniro/GrowableOres#4]
The create mechanical Harvester gets the items when it goes over the cane but doesn't break it.

https://github.com/skniro/GrowableOres/assets/147186856/34809d9d-8379-4549-8bee-4e33c7b9902f
This Is what was in the chest after.
![image_2023-10-06_105130296](https://github.com/skniro/GrowableOres/assets/147186856/017e06ac-0e68-43f0-ae04-ef53aab5784b)

**Comment by Antstone2898** [comment]
This was on fabric 1.20.1

**Comment by skniro** [comment]
I try add ore cane to some tags,but it isn't working,so i add a issue in create to ask create's developer how to fix it. Thanks your report!

**Comment by skniro** [comment]
Create team have closed my issue, so i think they have fixed this issue.
