### ISSUE TITLE
Add Better Nether compatible

### ISSUE THREAD

**Issue by skniro** [skniro/GrowableOres#8]

**Comment by Knito58** [comment]
Glowstone?

**Comment by skniro** [comment]
> Glowstone?

1.20.1-1.7.0+(Fabric) have been glowstone cane.

**Comment by skniro** [comment]
> Glowstone?

And if you want add new item please open a new issue.

**Comment by Knito58** [comment]
ok

**Comment by Knito58** [comment]
Thank you!
