### ISSUE TITLE
1.20.4 is missing some vanilla reeds

### ISSUE THREAD

**Issue by CassieRoseZA** [skniro/GrowableOres#9]
The Slime Reed doesn't exist in 1.20.4 and probably a few others

**Comment by CassieRoseZA** [comment]
Just looming at the code there's alot missing between the 2

**Comment by skniro** [comment]
It should be only 1.20.1 Fabric.Because it texture and other works aren't finished. I promise it will be added to 1.16.5 1.18-1.19.4 and 1.20.4.

**Comment by skniro** [comment]
Finished on forge 1.3.2 or1.3.3 fabric 1.7.3
